version: "3.8"
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: appdb
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - "${HOME}/postgres-data:/var/lib/postgresql/data:delegated"
      - "${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql"
  web:
    build: .
    environment:
      - API_DATABASE_URL=postgresql+asyncpg://root:root@db/appdb
      - API_SYNC_DATABASE_URL=postgresql://root:root@db/appdb
      - WAIT_HOSTS=db:5432
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
