BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 283d09733e29

CREATE TYPE dogtype AS ENUM ('terrier', 'bulldog', 'dalmatian');

CREATE TABLE dogs (
    pk INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0 CYCLE), 
    name VARCHAR(100), 
    kind dogtype, 
    PRIMARY KEY (pk)
);

CREATE INDEX ix_dogs_kind ON dogs (kind);

CREATE INDEX ix_dogs_pk ON dogs (pk);

CREATE TABLE timestamps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0 CYCLE), 
    timestamp INTEGER, 
    PRIMARY KEY (id)
);

CREATE INDEX ix_timestamps_id ON timestamps (id);

INSERT INTO alembic_version (version_num) VALUES ('283d09733e29') RETURNING alembic_version.version_num;
INSERT INTO timestamps (timestamp) VALUES (12), (10);
INSERT INTO dogs (name, kind) VALUES
                                  ('Bob', 'terrier'),
                                  ('Marli', 'bulldog'),
                                  ('Snoopy', 'dalmatian'),
                                  ('Rex', 'dalmatian'),
                                  ('Pongo', 'dalmatian'),
                                  ('Tillman', 'bulldog'),
                                  ('Uga', 'bulldog');

COMMIT;
